# https://travis-ci.org/#!/phlax/bcp47
language: python
python:
  - "3.5"

install:
  - pip install -U setuptools pip
  - pip install -e .
  - pip install .[test]

script:
  - flake8 .
  - pytest -vv

after_success:
  - codecov
